# Generated by Django 4.2.4 on 2023-08-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jop_type',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time')], default='Full time', max_length=15),
        ),
    ]
