# Generated by Django 4.2.4 on 2023-08-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_descraption'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='puplished_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
